#!/usr/bin/python3
"""
    Scrape and parse html file
    to setup holberton project directories
"""


def usage(argv):
    """
    --------------
    Method: usage
    --------------
    Description:
        Check if script is run with the
        proper number of arguments
    Args:
        @argv: List of Strings
            list of arguments retrieved
            from sys
    --------------
    """

    if len(argv) != 2:
        print("Usage: ./main.py <project number>")
        exit(1)

def format_dir(pwd):
    """
    --------------
    Method: format_dir
    --------------
    Description:
        Format a given directory path
        into a more usable format
    Args:
        @pwd: String
            Current working directory
    --------------
    """

    dirs = pwd.split('/')
    if len(dirs) < 2:
        print("Please check root directory and repo directory.")
        exit(1)
    result = "{}/{}".format(dirs[-2], dirs[-1])
    return result

def check_pwd(pwd, proj_dir):
    """
    --------------
    Method: chech_pwd
    --------------
    Description:
        Checks if current project folder structure
        is correct
    Args:
        @pwd: String
            formatted current working directory
        @proj_dir: String
            expected project directory
    --------------
    """

    pwd = format_dir(pwd)
    if proj_dir != pwd:
        print("PWD is the wrong directory.")
        exit(1)

def get_html(proj_num):
    """
    --------------
    Method: get_html
    --------------
    Description:
        Download project page as Html and
        Return a list of lines
    Args:
        @proj_num: Integer as String
            Desired holberton project number
    --------------
    """

    scraper = Scraper()
    return scraper.scrape(proj_num)

def parse_html(html):
    """
    --------------
    Method: parse_html
    --------------
    Description:
        Traverse html and
        Retrive desired data
    Args:
        @html: List of Strings
            Line by Line html data
    --------------
    """

    parser = Parser(html)
    html_data = {
        "learning_objectives": parser.get_objectives(),
        "project_directory": parser.get_proj_dir(),
        "project_files": parser.get_files()
    }
    return (html_data)

def create_files(files):
    """
    --------------
    Method: create_files
    --------------
    Description:
        create project files in project directory
        if the files don't already exist
    Args:
        @files: List of Strings
            list of file names
    --------------
    """

    from os import path

    for file in files:
        if path.exists(file):
            continue
        else:
            with open(file, 'w') as f:
                f.write("")

if __name__ == "__main__":
    from __init__ import *

    usage(argv)
    proj_num = argv[1]

    html = get_html(proj_num)
    html_data= parse_html(html)

    learn_objectives = html_data["learning_objectives"]
    proj_dir = html_data["project_directory"]
    files = html_data["project_files"]

    pwd = getcwd()
    check_pwd(pwd, proj_dir)
    create_files(files)

    print()
    for item in learn_objectives:
        print(item)
    print()
    print(proj_dir, "\n")
    for item in files:
        print(item)
